import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Anneldah | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="./dist/output.css" rel="stylesheet"/>
      </Head>

      <body>
        <h1 class="text-3xl font-bold underline">Anneldah yu are strong mama!</h1>
      </body>

      
    </div>
  )
}
